test_absolute (__main__.TestExercice) ... ok
test_factorial (__main__.TestExercice) ... ok
test_prefixes (__main__.TestExercice) ... ok
test_summation (__main__.TestExercice) ... FAIL
test_verify_ages (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_summation (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 50, in test_summation
    'Mauvaise réponse'
AssertionError: 5150.0 != 24133 : Mauvaise réponse

======================================================================
FAIL: test_verify_ages (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 77, in test_verify_ages
    'Mauvaise réponse'
AssertionError: Lists differ: [True, True, True, False, True, True, True, True, False] != [False, True, False, False, True, True, True, True, False]

First differing element 0:
True
False

- [True, True, True, False, True, True, True, True, False]
+ [False, True, False, False, True, True, True, True, False] : Mauvaise réponse

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=2)
